### ISSUE TITLE
Decode from iterator

### ISSUE THREAD

**Issue by kpcyrd** [marshallpierce/rust-base64#101]
Since the 0.10 release removed support for ignoring whitespace I looked into stripping whitespace myself and I found the snippet in the release notes:
```
filter(|b| !b" \n\t\r\x0b\x0c".contains(b)
```
We could avoid copying the content by having a function that can decode from an iterator so we can stream the filtered bytes.

**Comment by marshallpierce** [comment]
That would be convenient, for sure, but I don't see a clear path to make it fast. A big part of the reason the crate is fast is that it can decode and encode from slices.

**Comment by partim** [comment]
A compromise would be to allow decoding a sequence of slices. It would just have to keep some state from the potentially incomplete end of a slice between iterations.

**Comment by marshallpierce** [comment]
That sounds like the decode-side equivalent of the existing `EncoderWriter`. Shouldn't be too hard to adapt an iterator to a `Read`, I would imagine...

**Comment by partim** [comment]
Perhaps a `DecoderWriter` would be more convenient? I.e., a writer that is fed encoded data and writes decoded data to the underlying writer. That works neatly atop a vec.

**Comment by kanekv** [comment]
golang follows this pattern everywhere, e.g.: https://golang.org/pkg/encoding/base64/#NewDecoder

**Comment by AlexTMjugador** [comment]
My two cents here: with a crate like [`iter_read`](https://docs.rs/iter-read/0.3.0/iter_read/index.html) you can turn an iterator over bytes to a `Read` that can then be used with the `DecoderReader` struct of this crate. This doesn't involve collecting the entire input data to a temporary buffer again.

**Comment by marshallpierce** [comment]
That sounds like a good solution. (The DecoderReader will buffer chunks internally, so there's still some buffering.)
