### ISSUE TITLE
Crate Documentation Link

### ISSUE THREAD

**Issue by bencecile** [marshallpierce/rust-base64#104]
Hi, this was just something that I found when trying to get to the documentation for base64.
The link on crates.io (https://crates.io/crates/base64) just points to the README in the project repo.
I then looked up the crate on doc.rs and found the generated documentation (https://docs.rs/base64/0.10.1/base64/).

This is just a little thing that you might want to update so that it's nicer for other people.

**Comment by marshallpierce** [comment]
Indeed, that does seem like a nice thing.
