### ISSUE TITLE
Consider releasing a v0.11

### ISSUE THREAD

**Issue by CryZe** [marshallpierce/rust-base64#118]
It looks like the last release has been at the beginning of the year, so it's been quite a while and master contains the no_std support that I would like to use in my crate. I'm still blocked by a few other crates as well, but I'd like to merge no_std support in my crate sooner rather than later. So if you don't mind, I'd appreciate a v0.11 within the near future.

**Comment by marshallpierce** [comment]
Absolutely! I'm traveling right now but I'll be back in a few days and I'll get the release done.

**Comment by marshallpierce** [comment]
Done, sorry for the delay.
