### ISSUE TITLE
Where has MIME gone?

### ISSUE THREAD

**Issue by P-E-Meunier** [marshallpierce/rust-base64#125]
I just upgraded from an old version of this crate, and it seems the support for MIME is gone, and also the Config struct has changed. What should I do?

**Comment by marshallpierce** [comment]
MIME is simply standard base64 with 76-character CRLF line wraps. Line wrapping has been pulled out into its own crate: https://crates.io/crates/line-wrap. [An example in the line-wrap docs](https://docs.rs/line-wrap/0.1.1/line_wrap/#examples) shows how to do the equivalent to what was the MIME config.

**Comment by P-E-Meunier** [comment]
Thanks a lot! I guess this could be added as a note in the documentation.

**Comment by P-E-Meunier** [comment]
Wait, the decoding part is not in the line-wrap crate.

**Comment by marshallpierce** [comment]
This is all in the release notes, including the exact snippet that used to be used to remove whitespace for decoding: https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md#0100

It greatly complicated the implementation to have these things built into base64 itself, as well as preventing it from supporting `no_std`, hence the separation.
