### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by s97712** [marshallpierce/rust-base64#131]
```
error[E0423]: expected function, found module `base64::encode`
  --> src/common/aliyun.rs:51:16
   |
51 |     let sign = base64::encode(hmac.result().code());
   |                ^^^^^^^^^^^^^^ not a function

error[E0603]: module `encode` is private
```
## Version
- rust-base64: 0.12.0
- rust: rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)

**Comment by marshallpierce** [comment]
That nightly is a bit out of date. 1.44 is currently in beta, and nightly is 1.45. I don't see that issue with stable, beta, or nightly:

```
% rustup run nightly rustc --version 
rustc 1.45.0-nightly (647016923 2020-04-28)
% rustup run beta rustc --version
rustc 1.44.0-beta.2 (b1162ed50 2020-04-25)
% rustup run stable rustc --version
rustc 1.43.0 (4fb7144ed 2020-04-20)
```

Try updating your nightly and see if that helps?

**Comment by marshallpierce** [comment]
Re-open if it becomes reproducible.

**Comment by marshallpierce** [comment]
Is this a no_std issue? Try using https://docs.rs/base64/0.13.0/base64/fn.decode_config_slice.html.

**Comment by czyczk** [comment]
> Is this a no_std issue? Try using https://docs.rs/base64/0.13.0/base64/fn.decode_config_slice.html.

Thank you, I figured it out with your help. The ink! contract allows the "alloc" feature, and I see `encode()` is available as a function with the "alloc" feature on. So I brought back the "alloc" feature and got it fixed.
So only when "std" is off, `decode` and `encode` will be exposed as private modules not functions. Maybe this should go into README as a little note?
