### ISSUE TITLE
Minimum supported Rust version was bumped in 0.12.2

### ISSUE THREAD

**Issue by djc** [marshallpierce/rust-base64#135]
The changes in https://github.com/marshallpierce/rust-base64/commit/93fe059a1d3d5234be0945f89221e36054895801 cause 0.12.2 to be incompatible with 1.39.0, and rustls (as one user of base64) fixed base64 at 0.12.1. This is a bit unfortunate -- would it be okay to roll back the change for a while? Since base64 is such a low-level crate, it seems like being careful about minimum supported Rust version would be good.

**Comment by stjepang** [comment]
This also broke our builds in https://github.com/nats-io/nats.rs

**Comment by marshallpierce** [comment]
I'm looking into it. See also comments in https://github.com/marshallpierce/rust-base64/pull/133#issuecomment-646987891.

**Comment by marshallpierce** [comment]
Well that's really annoying. Current `master` works on 1.34.0, which we test in travis, and stable and nightly, but not 1.39.0, so our testing matrix didn't catch it.

**Comment by marshallpierce** [comment]
Should be fixed in 0.12.3. Thanks for the heads up on this issue.
