### ISSUE TITLE
Feature request: expose encoded_size() function

### ISSUE THREAD

**Issue by Veetaha** [marshallpierce/rust-base64#137]
Hi, it would be awesome if this crate exposed this function:
https://github.com/marshallpierce/rust-base64/blob/ad28eadc9886b6803a0e61f96e5f3fecbd9646f5/src/encode.rs#L284-L305

Having this function we would be able to know how many bytes to preallocate before encoding.
This is useful when we put the base64 sequence in the middle of the string, such that we could preallocate the memory for surrounding contents + base64 sequence.

My use case
I need to base64-encode protobuf message into a double-quoted string.
I know how many bytes protobuf message will take, but I don't know how many it will take in base64 form beforehand.

**Comment by marshallpierce** [comment]
That seems reasonable, though note that for your use case it may be ok to use a conservative estimate like `((byte len / 3) + 1) * 4`.

If the conservative estimate doesn't work for you, though, I'd be happy to take a PR to expose it.

**Comment by Veetaha** [comment]
Yup, I can definitely go with that, I'll submit a PR when I'd definitely require this feature, will leave the issue open for anyone else who might be interested to leave feedback

**Comment by marshallpierce** [comment]
Done in https://github.com/marshallpierce/rust-base64/pull/167.
