### ISSUE TITLE
Please provide a Writer that encodes to String

### ISSUE THREAD

**Issue by joshtriplett** [marshallpierce/rust-base64#141]
I'd like to use base64 as a `Writer`, so that I can use a serde serializer followed by base64, without an intermediate buffer. However, `base64::write::EncoderWriter` always wraps another `Writer`. I'd like to get a `String` out, so that I have a type-level guarantee of valid UTF-8 (which base64 will always produce). Would you consider adding a `base64::write::StringWriter` that writes to a `String`, and returns that string from `finish()`?

**Comment by marshallpierce** [comment]
That sounds reasonable.

**Comment by marshallpierce** [comment]
Does #142 address your use case?

**Comment by joshtriplett** [comment]
@marshallpierce Yes, that looks great! I left one comment there, about avoiding a copy of the data, but otherwise that would work perfectly for my use case.

**Comment by marshallpierce** [comment]
Released in v0.13.0.
