### ISSUE TITLE
Why panic on wrong length for decode_config_slice?

### ISSUE THREAD

**Issue by NilsIrl** [marshallpierce/rust-base64#147]
Why panic?

In case where the input is erroneous, there is no way of recovering because it panics.

**Comment by marshallpierce** [comment]
Can you help me understand your use case? Why would you call decode_config_slice without calculating the suitable decode buffer size? It's a programmer error to do so, so it's not going to conceivably be different if you retry like, say, an I/O error.

**Comment by NilsIrl** [comment]
If you expect a cryptographic key for example with a fixed size (e.g. 256 bit), I would declare a buffer to store that key and then use decode_config_slice to convert the key in base64 into the buffer.

**Comment by marshallpierce** [comment]
Wouldn't you check the input size first, in the same way you'd check a slice length before accessing `my_slice[123]`?

**Comment by NilsIrl** [comment]
> Wouldn't you check the input size first, in the same way you'd check a slice length before accessing `my_slice[123]`?

Yes, but with padding, wouldn't that be somewhat unclear?

**Comment by marshallpierce** [comment]
Good thought, but padding can add at most two characters, so the formula in https://docs.rs/base64/0.13.0/base64/fn.decode_config_slice.html will be safe.

**Comment by NilsIrl** [comment]
Ok, that's what I thought, for my specific use case, I can check for the precise number of characters, but I thought that maybe for less well behaved data (with spaces, newlines...) it becomes really hard to know before decoding how much data the encoded data has...

**Comment by marshallpierce** [comment]
Whitespace isn't allowed in base64, so it's not an issue. See https://github.com/marshallpierce/rust-base64/issues/105 for discussion on that.

**Comment by NilsIrl** [comment]
Thank you for the help! For my specific use case it works, and from what I understand it will work for basically every other use case as well, so everything's good!

**Comment by makoConstruct** [comment]
> Why would you call decode_config_slice without calculating the suitable decode buffer size?

I'm using base64 to store UUIDs. Each UUID is stored in a u128 (which becomes the output buffer), so the length of the output buffer is fixed, so I don't need to do a calculation to size it.

The input isn't trusted, though, so a check still needs to be done, the input might be too long. I can check the length myself, but I don't see why I should need to, as the decoder is clearly doing the checks itself, it just reports them via the wrong error model.

**Comment by marshallpierce** [comment]
You're using untrusted, unverified input with a slice and you're surprised by panics? The rest of the slice API is going to be a rude awakening for you, as it uses the "wrong" error model all over the place.

**Comment by makoConstruct** [comment]
I guess I'm not surprised that you're using the slice APIs that panic, but I'd be surprised if there aren't other versions that return results or options that you could be using instead, with equal or better performance after inlining.

If you added a check on the output buffer length, are there other reasons you'd expect this code could panic? Or, like, do just you not believe it's generally worth trying to write rust code that doesn't panic on untrusted input?

**Comment by marshallpierce** [comment]
It's not so much a question of if it's possible to return a Result, it's a question of if it makes sense in this case. It's a reasonable stance to say that using unknown input with a fixed size buffer is a programmer error, and that's the direction that Rust's slice API has taken in general. By using `decode_config_slice`, you are asserting that you _do_ know the length it should decode to, much like if you use, say, [`copy_from_slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice). If you don't know the length it should decode to, `decode_config` etc are better choices. The code should not panic for any other reasons, as documented. It is certainly worth writing code that doesn't panic on untrusted input, but there's a distinction between input of unknown contents and simply using the wrong size of buffer. The former is standard operating procedure for parsing; the latter is having incorrect logic.

All that being said, it's a nebulous distinction between what is considered recoverable vs a programmer error, and it's not possible to make a choice that's going to be right in all situations. http://joeduffyblog.com/2016/02/07/the-error-model/ is a thought provoking read on the matter. If, in your case, you really need a `Result`, I suggest writing a wrapper function that does whatever checks you need.

**Comment by makoConstruct** [comment]
> It's a reasonable stance to say that using unknown input with a fixed size buffer is a programmer error

It's going to be hard for me to swallow that given that reading UUIDs in objects sent from the network is the only application for base64 that I've had personally, in which case it's a completely reasonable error to want to be able to recover from, but okay, whatever, I must not have a broad enough perspective of normal applications of base64 encoding, keep not reporting this one type of error.
