### ISSUE TITLE
Encode/Decode compatibility with implementations of base64 from other languages

### ISSUE THREAD

**Issue by oscarbailey-tc** [marshallpierce/rust-base64#163]
Decoding a base64 string encoded using Python's builtin base64 module will produce an error. This is because their library inserts newline characters every 76 bytes:
https://docs.python.org/3/library/base64.html#base64.encode

This either needs to be highlighted in the documentation for this crate, or an "ignore_chars" option should be used for decoding (as with the Python implementation): 
https://docs.python.org/3/library/base64.html#base64.a85decode

Reference implementation I used for ignoring chars: https://rosettacode.org/wiki/Strip_a_set_of_characters_from_a_string#Rust

**Comment by marshallpierce** [comment]
This has been discussed ad nauseam; see other old issues. You will not have much luck convincing me of the soundness of an API design decision because "Python did it". :)

**Comment by oscarbailey-tc** [comment]
I spent the last couple of hours debugging this, it would be helpful for other devs if this was at least highlighted in the docs. It may be a poor design choice by Python, but that shouldn't impact the productivity of devs trying to decode a base64 string in Rust!

**Comment by marshallpierce** [comment]
But you don't have a Base64 string. You have some possibly valid base64 characters intermingled with other miscellaneous bytes. If the decode functions didn't correctly report an invalid byte, that's a bug and will be fixed. If they did, then what more could possibly done to identify the problem?

**Comment by marshallpierce** [comment]
Put differently: would you expect a jpeg or mp3 or x509 decoder to just ignore bytes that didn't match? Of course not.

**Comment by oscarbailey-tc** [comment]
Without an intimite knowledge of the Python implementation base64 encoder, I expect a base64 string to be produced. Attempting to decode that string with this crate will cause an error. I don't have a strong opinion opinion about what constitutes correct base64, but the fact is that Python is a very popular language, base64 provides a convinient way to transfer data between languages, and as a result future devs using your crate will run into this problem.

It would be helpful if you included this info in the docs more prominently, or perhaps checked whether the char is whitespace on a decode error and change the message accordingly.

**Comment by marshallpierce** [comment]
But decoding did tell you exactly which byte was wrong and where it was, correct?

**Comment by oscarbailey-tc** [comment]
It did. When I came accross this issue with your crate, I was having problems decoding a base64 string from a JSON file using another Rust crate. Having both problems to deal with at once complicated the debugging process.

This is an issue of helpfulness rather than correctness. I'm new to Rust, as many devs are, so having crates that "just work", or highlight common falling points is invaluable and will help this language succeed.

**Comment by oscarbailey-tc** [comment]
Also I do agree, it did suprise me when reading the Python docs that it inserts whitespace 😄

**Comment by marshallpierce** [comment]
I'm sorry that you've had a frustrating experience, but I don't really see how putting a comment in the docs somewhere would be more useful than an a detailed error that says exactly what the problem is and where it lies. I don't understand how seeing an invalid byte error with byte = 10 could be handled any faster than looking on asciitable.com and seeing that decimal 10 = new line.

**Comment by xmo-odoo** [comment]
@marshallpierce for what that's worth, having a configuration mode supporting this kind of things would be useful:

* to handle PEM/MIME base64, which I expect is what Python is producing here (specifiically MIME, PEM uses line lengths of 64 bytes while MIME uses 76), this is after all the origin of base64 so implementations especially older ones generating that by default would be logical, RFC 4880 (OpenPGP) also uses an extended version of MIME64.
* for compatibility with "legacy" systems e.g. while I have not tried others both Python and Ruby will strip invalid content by default (they also present some odd behaviour around `=`, and Ruby is apparently even more lenient than Python is, which is a lot)

I don't think this should be the default behaviour, but I figure the ability to enable this via the config would inform the user of the feature (and thus the possibility), and allow for providing additional and clearly labelled config constants.

**Comment by marshallpierce** [comment]
I don't want to get into the game of more config options for various legacy flavors. It's not a good use of my very limited OSS time, as it significantly increases code complexity for little benefit. Users presented with specific needs like various invalid tokens (whitespace or not) or other non-base64 framing should do whatever their situation demands to end up with _just_ base64 that can then be easily decoded, rather than expecting a base64 library to support all these other non-base64 concerns.

**Comment by oscarbailey-tc** [comment]
> significantly increases code complexity 

Would it not be the case of adding an extra value to the config here: 
https://docs.rs/base64/latest/src/base64/lib.rs.html#164-170

Then adding a filter step on decode?

The simple method being an `ignore_chars` option as suggested in my original post, or even `ignore_whitespace`.

I'm sure someone else would be willing to do the work and create the PR - I'm happy to contribute!

**Comment by marshallpierce** [comment]
Even if you can find a way to do that that doesn't sacrifice speed or no_std compatibility and doesn't increase implementation complexity or testing burden, it STILL wouldn't be a conceptual fit for a base64 decoding library. Removing framing is not base64's problem in the same way that removing TCP framing is not a JPEG library's problem.

**Comment by marshallpierce** [comment]
Furthermore, I don't get why people are so insistent on this niche case being implemented in the core of base64 itself. PEM is small, so you could easily remove things from a `Vec<u8>` with filtering you wish. Or, you can implement a `Read` that wraps whatever your weird framing-laden data source is to remove the unneeded fluff, and use `DecoderReader` on the resulting filtered stream. Why are these insufficient? The exact same filtering would take place in any case.

**Comment by marshallpierce** [comment]
Line feeds are part of MIME/PEM, not base64.

This thought-virus of wanting to skip invalid input that's intermingled with valid input needs to stop. It will not happen until you can explain to me why it is also a good idea for _literally every other format_ to also support this same concept. Why not just read base64 straight out of a .tar, skipping any tar-related metadata while we're at it.
