### ISSUE TITLE
Return partial decode on error

### ISSUE THREAD

**Issue by jasonish** [marshallpierce/rust-base64#169]
More of a question... I have a need for a parser that will return whats been decoded so far on error. Would this be in scope for this project as a configuration option?  I think its a little different than implementing a forgiving decoder.

**Comment by marshallpierce** [comment]
Hmm... What about a loop that decodes 4 symbols at a time and accumulating each resulting chunk of 3 decoded bytes?

**Comment by marshallpierce** [comment]
Idle.
