### ISSUE TITLE
Error when trying to decode \n byte

### ISSUE THREAD

**Issue by frozberry** [marshallpierce/rust-base64#172]
Trying to decode following  [this base64 string](https://cryptopals.com/static/challenge-data/6.txt) fails.

```
 let input = fs::read("challenge6.txt")?;
 let decoded = base64::decode(input)?;
```

This throws `Error: InvalidByte(60, 10)`. Byte 10 is the newline byte.

**Comment by marshallpierce** [comment]
Newline is not a valid token in the base64 alphabet, so the error is correct. See also e.g. https://github.com/marshallpierce/rust-base64/issues/163 or https://github.com/marshallpierce/rust-base64/issues/105.
