### ISSUE TITLE
please release an alpha version (`0.14.0-alpha.1`)

### ISSUE THREAD

**Issue by zseri** [marshallpierce/rust-base64#173]
I want to use the new `Alphabet` abstraction to use a custom alphabet (`URL_SAFE` with `-` replaced with `+` for easier shell usage of files named with a base64-encoded hash), but no pre-release version has yet been published on `crates.io`, and I usually want to avoid relying on git dependencies (because fetching them is harder because it needs `git`), even for pre-not-yet-stable stuff. Such a release might also have the advantage that more people would test it and e.g. detect more edge cases that should be handled more idiomatically or such...

**Comment by marshallpierce** [comment]
That's reasonable. I'll release an alpha when I get a moment.

**Comment by marshallpierce** [comment]
Here you go: https://crates.io/crates/base64/0.20.0-alpha.1. Please let me know if you have any feedback.
