### ISSUE TITLE
[Request] Consider adding in-place operations

### ISSUE THREAD

**Issue by c410-f3r** [marshallpierce/rust-base64#183]
Such thing is probably possible for decoding but I am not sure about encoding. See https://github.com/dotnet/corefxlab/issues/786

For example, `(decode|encode)_engine_slice(T, &mut [u8], &E)` would then be `(decode|encode)_engine_slice(&mut [u8], &E)` or `(decode|encode)_engine_slice(&mut BUFFER, &E)` where `BUFFER` is a trait bound for anything that implements `push`, `pop`, `as_ref`, `truncate`, `clear` or whatever for arrays/vectors/slices of bytes.

**Comment by marshallpierce** [comment]
I can see how that could be useful.

**Comment by c410-f3r** [comment]
Closing due to the lack of activeness.
