### ISSUE TITLE
Add `RFC 2045` standard

### ISSUE THREAD

**Issue by FreePhoenix888** [marshallpierce/rust-base64#200]
https://en.wikipedia.org/wiki/Base64#:~:text=RFC%202045%3A%20Base64%20transfer%20encoding%20for%20MIME

**Comment by marshallpierce** [comment]
You can define any alphabet you want: https://docs.rs/base64/0.20.0-alpha.1/base64/alphabet/struct.Alphabet.html

0.20.0-alpha.1 is fine to use in production as long as you're OK with some relatively minor further changes before 0.20.0, which is coming out soon.

**Comment by FreePhoenix888** [comment]
> You can define any alphabet you want: https://docs.rs/base64/0.20.0-alpha.1/base64/alphabet/struct.Alphabet.html
> 
> 0.20.0-alpha.1 is fine to use in production as long as you're OK with some relatively minor further changes before 0.20.0, which is coming out soon.

Thank you
