### ISSUE TITLE
Unable to decode base64 encoded content from github api

### ISSUE THREAD

**Issue by FreePhoenix888** [marshallpierce/rust-base64#201]
Github api response with content field: https://api.github.com/repos/linksplatform/Disposables/contents/csharp/Platform.Disposables/Platform.Disposables.csproj?ref=main

Error: InvalidByte

**Comment by marshallpierce** [comment]
The content field ends with "\n", which is not a valid base64 token. See https://github.com/marshallpierce/rust-base64#i-need-to-decode-base64-with-whitespacenull-bytesother-random-things-interspersed-in-it-what-should-i-do

**Comment by FreePhoenix888** [comment]
> The content field ends with "\n", which is not a valid base64 token. See https://github.com/marshallpierce/rust-base64#i-need-to-decode-base64-with-whitespacenull-bytesother-random-things-interspersed-in-it-what-should-i-do

Thank you!
