### ISSUE TITLE
Precise length checking in `decode_slice`

### ISSUE THREAD

**Issue by marshallpierce** [marshallpierce/rust-base64#210]
It would be good to have the length error only emitted when we know it to be required.

**Comment by davidzeng0** [comment]
Any chance this gets fixed?

**Comment by marshallpierce** [comment]
> Any chance this gets fixed?

You're welcome to propose a PR.

**Comment by davidzeng0** [comment]
What's going on with pull #227? Is it stalled? It seems like it fixes a lot of issues. Let me know if I should start fresh or continue from that pull request.

**Comment by marshallpierce** [comment]
I don't know the status. Presumably the author got busy with real life, etc. Small PRs are more likely to be reviewed and merged promptly since they require smaller blocks of time to review.

**Comment by mqudsi** [comment]
Note that this is appears to be a regression. Code used to work fine with base64 0.13 now returns an incorrect `OutputSliceTooSmall` error under 0.21.

**Comment by marshallpierce** [comment]
Hm, that's not good. I'll see if I can find time to address this myself.

**Comment by marshallpierce** [comment]
Fix released in 0.22.0.

**Comment by mqudsi** [comment]
Thanks! 🙏
