### ISSUE TITLE
How do I change the padding character?

### ISSUE THREAD

**Issue by ShayBox** [marshallpierce/rust-base64#215]
I'm trying to use Base64R from [No-Chat-Reports](https://github.com/HKS-HNS/No-Chat-Reports/blob/45327294178fd131732892647fa0e9949aca5cb1/src/main/java/com/aizistral/nochatreports/encryption/Encryptor.java#L206)   
I believe I have the alphabet working but the padding character is also changed, how do I change the padding character with this crate?

```rust
const BASE64R: &str = "!\"#$%¼'(),-.:;<=>?@[\\]^_`{|}~¡¢£¤¥¦¨©ª«¬®¯°±²³µ¶·¸¹º0123456789+»";
```

**Comment by marshallpierce** [comment]
My condolences for having to work with such an utterly ridiculous format. The padding byte is not configurable. Padding is useless anyway, but I suggest just replacing those bytes after encoding and before decoding if you must have it.
