### ISSUE TITLE
Using this crate easier

### ISSUE THREAD

**Issue by ssrlive** [marshallpierce/rust-base64#225]
Since base64 crate is not friendly to new users likes mentioned in #213, so I think it's necessary to wrapping this crate. like this:
```rust
use base64::{engine::general_purpose, Engine as _};

/// The base64 encoding engine to use when encoding/decoding data.
#[derive(Debug, Clone, Copy)]
pub enum Base64Engine {
    /// Base64 Standard
    Standard,
    /// Base64 StandardNoPad
    StandardNoPad,
    /// Base64 UrlSafe
    UrlSafe,
    /// Base64 UrlSafeNoPad
    UrlSafeNoPad,
}

pub fn base64_encode(bytes: &[u8], engine: Base64Engine) -> String {
    match engine {
        Base64Engine::Standard => general_purpose::STANDARD.encode(bytes),
        Base64Engine::StandardNoPad => general_purpose::STANDARD_NO_PAD.encode(bytes),
        Base64Engine::UrlSafe => general_purpose::URL_SAFE.encode(bytes),
        Base64Engine::UrlSafeNoPad => general_purpose::URL_SAFE_NO_PAD.encode(bytes),
    }
}

pub fn base64_decode(
    b64str: &str,
    engine: Base64Engine,
) -> Result<Vec<u8>, base64::DecodeError> {
    match engine {
        Base64Engine::Standard => general_purpose::STANDARD.decode(b64str),
        Base64Engine::StandardNoPad => general_purpose::STANDARD_NO_PAD.decode(b64str),
        Base64Engine::UrlSafe => general_purpose::URL_SAFE.decode(b64str),
        Base64Engine::UrlSafeNoPad => general_purpose::URL_SAFE_NO_PAD.decode(b64str),
    }
}
```
thus we can use this crate easier.

**Comment by marshallpierce** [comment]
You're welcome to wrap this library any way you like in your own code, of course, but this library will not be adopting that API. It is a non-goal to support everyone's favorite style all at the same time. It _is_ a goal to provide an API that users can compose reliably and safely, optionally wrapping it to suit their preferences, and that's been done.

**Comment by marcodpt** [comment]
Using version 0.20!

I am not in a position to understand all the complexities of a character system and my goal is simply to look for a library that abstracts those complexities while I focus on other problems.

Gratitude for the work done, my Cargo.toml is stuck in version 0.20
