### ISSUE TITLE
Design choices 

### ISSUE THREAD

**Issue by NikosEfthias** [marshallpierce/rust-base64#228]
# The problem
The api used to be very simple `base64::{encode,decode}`. Which suited needs of many people.\
Now theres no many words involved to do a simple standart base64 encoding.

# How I, the issue filer, am going to help solve it

I propose undeprecating the encode decode under base64 top level and do all those Engine::GeneralPurpose stuff inside of it away from the user

**Comment by ssrlive** [comment]
Since the author will *NOT* change his mind, you can refer #225 to wrapping this crate. or switch to https://crates.io/crates/data-encoding instead.

**Comment by NikosEfthias** [comment]
@ssrlive i do kind of understand the author however this is something so minor and it was in the code initially already.
This is something sadly i see in rust people sometimes we tend to make things unnecessarily complicated for no real benefit.
As seen in this crate the author went out of his way to complicate a crate that was designed very beginner friendly and nice earlier

**Comment by Nugine** [comment]
You can also switch to [base64-simd](https://docs.rs/base64-simd) for a simple API design and much better performance.

**Comment by DoumanAsh** [comment]
You can consider much minimal crate [based64](https://crates.io/crates/based64)
It only provides API for basic stuff that you need, rather than having complicated and unnecessary shit

**Comment by marshallpierce** [comment]
It's a non-goal of this library to include every user's favorite API variant. Having too many ways of doing things increases the cognitive burden for users trying to learn the library's API.

If you have a preferred API style that you want to invoke in your project, then you are free to adapt this library to suit your purpose by writing a few small functions, etc. Or, by all means go use some other library if writing those functions is too much of a burden.
