### ISSUE TITLE
How to generate the base64 format like openssl command

### ISSUE THREAD

**Issue by RickSKy** [marshallpierce/rust-base64#235]
'/usr/bin/openssl base64'  can crate base64 string. And I try to use  '/usr/bin/openssl base64 -d ' to decode the message which rust-base64 generated, but it failed. I have tried general_purpose::STANDARD_NO_PAD , URL_SAFE_NO_PAD, STANDARD, URL_SAFE. 
Thanks

**Comment by marshallpierce** [comment]
Can you be more specific about "it failed"?
