### ISSUE TITLE
GeneralPurpose engine should implement Clone and Debug

### ISSUE THREAD

**Issue by xfbs** [marshallpierce/rust-base64#242]
# The problem

- `GeneralPurpose` engine should implement some common traits. Definitely needed are `Clone` and `Debug`, optionally good would be `PartialEq`, `Hash`, and some others.

# How I, the issue filer, am going to help solve it

- I can make a PR if needed or provide more information why these traits are very important.

**Comment by marshallpierce** [comment]
I'm curious, what's the use case? Why would you be comparing engine instances, or using them as map keys? Or using Debug to see their internal lookup tables, etc?

**Comment by Kinrany** [comment]
It would be nice to be able to store a dynamically selected engine in a cloneable struct.

Though the more general argument is that foreseeing all use cases is impossible and Rust does not allow implementing traits in depending crates: https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits

**Comment by Kinrany** [comment]
The derived impl is fine, and it can always be changed later because Debug is explicitly not stable.

**Comment by marshallpierce** [comment]
I'll release a new version with the fix soon.

**Comment by marshallpierce** [comment]
0.21.5 released with this fix.
