### ISSUE TITLE
Make `Alphabet::from_str_unchecked` `pub const unsafe`

### ISSUE THREAD

**Issue by Colerar** [marshallpierce/rust-base64#245]
Then it's possible to create `const` custom alphabet outside this crate:

```rust
pub const MY_CUSTOM_ALPHABET: Alphabet = unsafe {
  Alphabet::from_str_unchecked(
      "..." /* custom alphabet string */,
  )
};
```

For `Alphabet::new`, the return type is `Result`, so I cannot unwrap it in `const` context:

```rust
const MY_CUSTOM_ALPHABET: Alphabet = base64::alphabet::Alphabet::new(
    "..." /* custom alphabet string */,
)
.unwrap();
```

The compiler complains:

```plaintext
error[E0015]: cannot call non-const fn `Result::<Alphabet, ParseAlphabetError>::unwrap` in constants
  --> src/main.rs:35:2
   |
35 | .unwrap();
   |  ^^^^^^^^
   |
   = note: calls in constants are limited to constant functions, tuple structs and tuple variants
```

**Comment by lamgea** [comment]
That makes a lot more sense. I was wondering why it is `const` but return `Result` so that I can't use it in the constant context anyway.

**Comment by lamgea** [comment]
Oh wait, there was already a similar issue: #232

**Comment by marshallpierce** [comment]
Indeed... #232 shows how to use either `match` + `panic!` for a `const`, or `lazy_static` for a `static`. I'll add those to the docs to make it more discoverable.
