### ISSUE TITLE
Add encode_vec()

### ISSUE THREAD

**Issue by Timmmm** [marshallpierce/rust-base64#257]
It would be nice if there were an `encode_vec()` function that would encode to `Vec<u8>` instead of `String`.

**Comment by Timmmm** [comment]
Not very efficient though surely?

**Comment by marshallpierce** [comment]
A String wraps an inner Vec, so it just consumes the String and returns the Vec. https://doc.rust-lang.org/src/alloc/string.rs.html#849

**Comment by Timmmm** [comment]
Ah good point and I guess when you construct the string you're just appending characters so it doesn't have to deal with UTF-8. Fair enough.

I still think it would be nice to add this method as a convenience but up to you!
