### ISSUE TITLE
Question: best way to access inner field values

### ISSUE THREAD

**Issue by JosiahParry** [marshallpierce/rust-base64#265]
# The problem

I am writing [bindings](https://github.com/extendr/b64) to base64 for the R language. One of the hurdles I am encountering is accessing inner values. These are used for printing and fetching. Ideally, a user could create a default engine, then call a method to fetch the alphabet for that engine. Today, I'm unable to (easily) do so. 

Ideally, as a user, with an engine, I could extract the alphabet, and the config used for it. Then from that, extract the options in the config. I can do this only by passing the object to `format!("{x:?}")` for its debug method and processing the text it outputs. 

Are there better ways to do this? What would be specifically helpful would be:

1. Access a `GeneralPurposeConfig` field values either directly or by method e.g. `.get_encode_padding()`
2. Access a reference to a `GeneralPurpose`'s `Alphabet` and `GeneralPurposeConfig` so that
   1. An alphabet's characters can be fetched as well as determine the options used in the config

**Comment by marshallpierce** [comment]
What's the use case for printing those details? The fact that in all of the Rust usage of this lib nobody has ever needed those things (AFAIK) makes me suspect that that level of detail is not really useful.

**Comment by marshallpierce** [comment]
Also, I didn't know about extendr -- that's a neat R / Rust integration.

**Comment by JosiahParry** [comment]
Totally fair! My use case is more quality of life and introspection based more than anything. e.g from an R perspective: 

```r
eng <- engine("bcrypt")

cur_alphabet <- eng$alphabet
cur_config <- eng$config

# maybe some printing or reporting etc based on that who knows. 
```

 The bindings to base64 are far faster and far more flexible than the current standard in the R ecosystem. I doubt any further needs may arise. If so, I may come back to bother you again 🙃

**Comment by marshallpierce** [comment]
Sounds good. I'm glad it's useful.
