### ISSUE TITLE
Standard encode is too time consuming task

### ISSUE THREAD

**Issue by nricciardi** [marshallpierce/rust-base64#272]
I'm using `STANDARD.encode()` to encode an image in base64 for my Markdown compiler, so that images can be inserted in HTML without paths.

Profiling compilation executions, that operation is the most time consuming task (after `image::open()`). Is there a way to reduce the times?

Following Rust file: https://github.com/nricciardi/nmd/blob/main/src/resource/image_resource.rs

**Comment by marshallpierce** [comment]
What is the input data? How are you profiling? 

Also, what are you expecting? If base64 is the only thing you're doing to data after reading it from disk, then it is natural that base64 will be the next most time consuming thing. 

It is of course possible to optimize software more, and base64 is no exception. You could use `encode_slice` to avoid allocation, or you could parallelize image handling across all cores, or this library could have SIMD-based encoding, and so forth. Probably parallelization will be the best ROI. The benchmark `encode_large_input/encode/3145728` on an M2 processor shows it takes about 2ms to encode 3MiB of data (at about 1.4GiB/s), and of course quicker for smaller inputs. Even assuming only four threads, that would exceed the ability of most common storage systems to keep up.

**Comment by nricciardi** [comment]
I have changed images elaboration, so now they are smaller than before. Now, base64 encoding is not the most time-consuming task.
Thank you anyway.
